server:
  port: 8900
  
eureka:
   client:
      registerWithEureka: true
      fetchRegistry: true
      serviceUrl:
         defaultZone: http://localhost:8761/eureka
   instance:
    hostname: localhost 
  
spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
              allowedOrigins: "*"
              allowedMethods: "*"
              allowedHeaders: "*"
      routes:
        - id: IAM-SERVICE 
          uri: lb://IAM-SERVICE
          predicates:
            - Path=/authenticate/**, /user/**
        - id: ADMIN-SERVICE
          uri: lb://ADMIN-SERVICE
          predicates:
            - Path=/admin/**  
        - id: SCHEDULER-SERVICE
          uri: lb://SCHEDULER-SERVICE
          predicates:
            - Path=/schedule/**
        - id: PATIENT-SERVICE
          uri: lb://PATIENT-SERVICE
          predicates:
            - Path=/patient/**
            
            
            
        